# Site
name: "LegalAuctor"
title: "Legal Auctor"
description: "Legal Auctor - raise the bar the legal way"
logo: 'assets/images/logo_mod.png'
favicon: 'assets/images/logo_mod.png'
baseurl: /blog-jmishra
url: https://spacevstab.github.io/
# google_analytics: 'UA-46278016-1'
# disqus: 'demowebsite'
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  jaya:
    name: Jaya Mishra
    display_name: Jaya Mishra
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: jayamishra576@gmail.com
    web: https://legalauctor.com
    description: "Jaya Mishra of House Mishra, rightful heir to the Iron Throne, rightful Queen of the Andals, and the First Men, Protector of the Seven Kingdoms, the Mother of Dragons, the Khaleesi of the Great Grass Sea, the Unburnt, the Breaker of Chains. [to be updated]"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
